<?php

namespace IntakeBundle\Repository;

/**
 * AfspraakRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AfspraakRepository extends \Doctrine\ORM\EntityRepository
{
}
