<?php

namespace IntakeBundle\Repository;

/**
 * BeschikbaarheidRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeschikbaarheidRepository extends \Doctrine\ORM\EntityRepository
{
}
