<?php

namespace IntakeBundle\Repository;

/**
 * StudieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudieRepository extends \Doctrine\ORM\EntityRepository
{
}
